name: CI

on:
  push:
    branches: [master]
    tags: ['v*.*.*']
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools cmake patchelf python3-venv

      - name: Install Python dependencies
        run: |
          sudo pip3 install -U setuptools urllib3 requests
          sudo pip3 install build twine
          sudo pip3 install .

      - name: Run tests
        run: python3 test/test_run_bash_tests.py

      - name: Build package
        run: sudo python3 -m build

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: twine upload -u __token__ -p $PYPI_TOKEN dist/*
